// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GroceryItem struct {
	ID        pgtype.UUID
	Name      pgtype.Text
	CreatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
	BoughtAt  pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
